# name = "stackblitz-cr"
# compatibility_date = "2023-12-01"
# main = "./.output/server/index.mjs"
# workers_dev = true
compatibility_date = "2024-03-14"

# rules = [
#   { type = "ESModule", globs = ["**/*.js", "**/*.mjs"]},
# ]

# [site]
# bucket = ".output/public"

# kv_namespaces = [
#     { binding = "WORKFLOWS", id = "Workflows" }
# ]

[[r2_buckets]]
binding = 'BUCKET' # <~ valid JavaScript variable name
bucket_name = 'cr-bucket'


